using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{

    public float acceleration = 0;
    public float responsiveness = 1;
    public float friction = 0.5f;
    public float airAccelerationModifier = 0.2f;
    private Transform player;
    public Rigidbody wheel;
    public LayerMask groundLayers;

    void Start()
    {
        player = GetComponent<Transform>();
    }

    void FixedUpdate() {
        calculateForce();
        updatePosition();
    }

    void calculateForce() {
        Vector3 currentVelocity = wheel.velocity;

        // Calculates the force generated by the player pressing WASD

        Vector3 playerInputForce = (player.forward * Input.GetAxisRaw("Forward") + player.right * Input.GetAxisRaw("Sideways")).normalized * acceleration;

        // Okay so let me explain
        // Yes friction and stopping force are different. Stopping force slows you down when you stop pressing buttons
        // where friction reduces your max speed by slowing you down WHILE you drive.
        // Could they be condensed to the same variable? Dunno! ¯\_(ツ)_/¯
        Vector3 stoppingForce = Vector3.zero;
        Vector3 frictionForce = Vector3.zero;
        if (getGrounded()) {
            //Debug.Log("I am grounded :O");
            // Calculates friction
            frictionForce = -currentVelocity * friction;
            stoppingForce = (-currentVelocity + Vector3.Project(currentVelocity, playerInputForce)) * responsiveness;
            // If nothing is being pressed, boost your angular drag to slow your spinning
            if (playerInputForce.magnitude < 0.1) {
                wheel.angularDrag = 0.99f;
            } else {
                wheel.angularDrag = 0.05f;
            }
        } else {
            playerInputForce *= airAccelerationModifier;
        }
        // Adds the force
        wheel.AddForce(Time.fixedDeltaTime * (playerInputForce + stoppingForce + frictionForce), ForceMode.Acceleration);
    }

    void updatePosition() {
        player.position = wheel.position;
    }

    bool getGrounded() {
        return Physics.CheckBox(player.position + new Vector3(0, -0.5f, 0), new Vector3(0.4f, 0.2f, 0.4f), Quaternion.identity, groundLayers);
    }
}