using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{

    public float accelerationSpeed = 0;
    public float maxSpeed = 10;
    public float responsiveness = 1;
    public float friction = 0.5f;
    public float airAccelerationModifier = 0.2f;
    private Transform player;
    public Rigidbody wheel;

    void Start()
    {
        player = GetComponent<Transform>();
    }

    void Update()
    {
        calculateForce();
        updatePosition();

    }

    void calculateForce() {
        // TODO: max speed 
        Vector3 currentVelocity = wheel.velocity;
        // Calculates the force generated by player input
        Vector3 playerInputForce = accelerationSpeed * (Input.GetAxisRaw("Forward") * player.forward + Input.GetAxisRaw("Sideways") * player.right).normalized;
        // Calculates friction
        Vector3 frictionForce = Vector3.zero;
        if (getGrounded()) {
            //Debug.Log("I am grounded :O");
            frictionForce = -currentVelocity * friction;
            // If nothing is being pressed, boost your friction to stop you faster
            if (playerInputForce.magnitude < 0.1) {
                frictionForce *= responsiveness;
                wheel.angularDrag = 0.8f;
            } else {
                wheel.angularDrag = 0.05f;
            }
        } else {
            playerInputForce *= airAccelerationModifier;
        }
        // Adds the force
        wheel.AddForce(playerInputForce + frictionForce, ForceMode.Acceleration);
    }

    void updatePosition() {
        player.position = wheel.position;
    }

    bool getGrounded() {
        return Physics.CheckBox(player.position + new Vector3(0, -0.5f, 0), new Vector3(0.5f, 0.2f, 0.5f), Quaternion.identity, 64);
    }
}